[common]
# 基础输出，目标为 Mihomo Meta
target=clashmeta
# 自动移除旧代理提供者，保证输出不会出现proxy-providers
remove_proxy_provider=true
# 规则集下载使用的代理，解决规则集下载失败
rule-provider-proxy=DIRECT

[custom]
# 全局参数
mixed-port=7890
allow-lan=true
bind-address=*
ipv6=false
unified-delay=true
tcp-concurrent=true
log-level=info
keep-alive-idle=600
keep-alive-interval=15
external-controller=0.0.0.0:9090
secret=
external-ui=ui
external-ui-url=https://gh-proxy.com/https://github.com/Zephyruso/zashboard/archive/refs/heads/master.zip

[sniffer]
enable=true
http-port=80,8080-8880
http-override-destination=true
tls-port=443,8443
quic-port=443,8443
skip-domain=Mijia Cloud,+.push.apple.com

[tun]
enable=true
stack=mixed
dns-hijack=any:53,tcp://any:53
auto-route=true
auto-redirect=true
auto-detect-interface=true

[dns]
enable=true
cache-algorithm=arc
ipv6=false
enhanced-mode=fake-ip
fake-ip-range=198.18.0.1/16
fake-ip-filter-mode=blacklist
fake-ip-filter=*,+.lan,+.local,+.market.xiaomi.com
default-nameserver=223.5.5.5
nameserver=https://dns.alidns.com/dns-query,https://doh.pub/dns-query

[proxy-groups]
# 选择组
🚀 默认代理=select,♻️ 自动选择,🇭🇰 香港节点,🇯🇵 日本节点,🇸🇬 狮城节点,🇺🇲 美国节点,🌐 全部节点,直连
📹 YouTube=select,♻️ 自动选择,🇭🇰 香港节点,🇯🇵 日本节点,🇸🇬 狮城节点,🇺🇲 美国节点,🌐 全部节点,直连
🍀 Google=select,♻️ 自动选择,🇭🇰 香港节点,🇯🇵 日本节点,🇸🇬 狮城节点,🇺🇲 美国节点,🌐 全部节点,直连
👨🏿‍💻 GitHub=select,♻️ 自动选择,🇭🇰 香港节点,🇯🇵 日本节点,🇸🇬 狮城节点,🇺🇲 美国节点,🌐 全部节点,直连
🐬 OneDrive=select,♻️ 自动选择,🇭🇰 香港节点,🇯🇵 日本节点,🇸🇬 狮城节点,🇺🇲 美国节点,🌐 全部节点,直连
🪟 Microsoft=select,♻️ 自动选择,🇭🇰 香港节点,🇯🇵 日本节点,🇸🇬 狮城节点,🇺🇲 美国节点,🌐 全部节点,直连
🎵 TikTok=select,🇸🇬 狮城节点,♻️ 自动选择,🇭🇰 香港节点,🇯🇵 日本节点,🇺🇲 美国节点,🌐 全部节点,直连
📲 Telegram=select,♻️ 自动选择,🇭🇰 香港节点,🇯🇵 日本节点,🇸🇬 狮城节点,🇺🇲 美国节点,🌐 全部节点,直连
🎥 NETFLIX=select,♻️ 自动选择,🇭🇰 香港节点,🇯🇵 日本节点,🇸🇬 狮城节点,🇺🇲 美国节点,🌐 全部节点,直连
💶 Wallet=select,♻️ 自动选择,🇭🇰 香港节点,🇯🇵 日本节点,🇸🇬 狮城节点,🇺🇲 美国节点,🌐 全部节点,直连
🎮 Steam=select,♻️ 自动选择,🇭🇰 香港节点,🇯🇵 日本节点,🇸🇬 狮城节点,🇺🇲 美国节点,🌐 全部节点,直连
🍎 Apple=select,♻️ 自动选择,🇭🇰 香港节点,🇯🇵 日本节点,🇸🇬 狮城节点,🇺🇲 美国节点,🌐 全部节点,直连
🐟 漏网之鱼=select,🚀 默认代理,♻️ 自动选择,🇭🇰 香港节点,🇯🇵 日本节点,🇸🇬 狮城节点,🇺🇲 美国节点,🌐 全部节点,直连

# 自动测速组
♻️ 自动选择=url-test,.*,https://www.gstatic.com/generate_204,300,50,lazy=true
🤖 OpenAI=url-test,^((?!(港|HK|(?i)Hong|直连)).)*$,https://www.gstatic.com/generate_204,300,50,lazy=true
🧠 其他AI=url-test,^((?!(直连)).)*$,https://www.gstatic.com/generate_204,300,50,lazy=true

# 地区分组
🇭🇰 香港节点=select,(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$
🇯🇵 日本节点=select,(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$
🇸🇬 狮城节点=select,(?=.*(新加坡|坡|狮城|SG|(?i)Singapore))^((?!(台|日|韩|港|美)).)*$
🇺🇲 美国节点=select,(?=.*(美|US|(?i)States|America))^((?!(港|台|韩|新|日)).)*$
🌐 全部节点=select,.*

[rules]
# 【重点】下面这两条，专门规避订阅更新死锁：转换后端和gist域名强制直连
DOMAIN-SUFFIX,pages.dev,直连
DOMAIN-SUFFIX,gist.githubusercontent.com,直连

AND,((RULE-SET,cn!_domain),(DST-PORT,443),(NETWORK,UDP)),REJECT
RULE-SET,private_ip,直连,no-resolve
RULE-SET,private_domain,直连
RULE-SET,ads_domain,REJECT
RULE-SET,privacy_domain,REJECT
DOMAIN-SUFFIX,doubleclick.net,REJECT
DOMAIN-SUFFIX,googleadservices.com,REJECT
DOMAIN-SUFFIX,googlesyndication.com,REJECT
DOMAIN,pagead2.googlesyndication.com,REJECT
DOMAIN,googleads.g.doubleclick.net,REJECT
DOMAIN,ad.doubleclick.net,REJECT
DOMAIN,static.doubleclick.net,REJECT
DOMAIN,m.doubleclick.net,REJECT
DOMAIN,mediavisor.doubleclick.net,REJECT
DOMAIN-SUFFIX,openai.com,🤖 OpenAI
DOMAIN-SUFFIX,chatgpt.com,🤖 OpenAI
DOMAIN-SUFFIX,chat.openai.com,🤖 OpenAI
DOMAIN-SUFFIX,auth.openai.com,🤖 OpenAI
DOMAIN-SUFFIX,api.openai.com,🤖 OpenAI
DOMAIN-SUFFIX,oaiusercontent.com,🤖 OpenAI
DOMAIN-SUFFIX,oaistatic.com,🤖 OpenAI
RULE-SET,ai_domain,🧠 其他AI
RULE-SET,youtube_domain,📹 YouTube
RULE-SET,google_domain,🍀 Google
RULE-SET,github_domain,👨🏿‍💻 GitHub
RULE-SET,onedrive_domain,🐬 OneDrive
RULE-SET,microsoftcn_domain,直连
RULE-SET,microsoft_domain,🪟 Microsoft
RULE-SET,applecn_domain,直连
RULE-SET,apple_domain,🍎 Apple
RULE-SET,telegram_domain,📲 Telegram
RULE-SET,tiktok_domain,🎵 TikTok
RULE-SET,netflix_domain,🎥 NETFLIX
RULE-SET,paypal_domain,💶 Wallet
RULE-SET,binance_domain,💶 Wallet
RULE-SET,okx_domain,💶 Wallet
RULE-SET,usd_domain,💶 Wallet
RULE-SET,steamcn_domain,直连
RULE-SET,steam_domain,🎮 Steam
RULE-SET,cn!_domain,🚀 默认代理
RULE-SET,cn_domain,直连
RULE-SET,google_ip,🍀 Google
RULE-SET,apple_ip,🍎 Apple
RULE-SET,telegram_ip,📲 Telegram
RULE-SET,netflix_ip,🎥 NETFLIX
RULE-SET,cn_ip,直连
MATCH,🐟 漏网之鱼

[rule-providers]
private_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/private.mrs,interval=86400,behavior=domain,format=mrs
ads_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/ad.mrs,interval=86400,behavior=domain,format=mrs
privacy_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/privacy.mrs,interval=86400,behavior=domain,format=mrs
ai_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/ai.mrs,interval=86400,behavior=domain,format=mrs
youtube_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/youtube.mrs,interval=86400,behavior=domain,format=mrs
google_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/google.mrs,interval=86400,behavior=domain,format=mrs
github_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/github.mrs,interval=86400,behavior=domain,format=mrs
onedrive_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/onedrive.mrs,interval=86400,behavior=domain,format=mrs
microsoft-cn_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/microsoft-cn.mrs,interval=86400,behavior=domain,format=mrs
microsoft_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/microsoft.mrs,interval=86400,behavior=domain,format=mrs
apple-cn_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/apple-cn.mrs,interval=86400,behavior=domain,format=mrs
apple_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/apple.mrs,interval=86400,behavior=domain,format=mrs
telegram_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/telegram.mrs,interval=86400,behavior=domain,format=mrs
tiktok_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/tiktok.mrs,interval=86400,behavior=domain,format=mrs
netflix_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/netflix.mrs,interval=86400,behavior=domain,format=mrs
paypal_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/paypal.mrs,interval=86400,behavior=domain,format=mrs
binance_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/binance.mrs,interval=86400,behavior=domain,format=mrs
okx_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/okx.mrs,interval=86400,behavior=domain,format=mrs
crypto_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/crypto.mrs,interval=86400,behavior=domain,format=mrs
steam-cn_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/steam-cn.mrs,interval=86400,behavior=domain,format=mrs
steam_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/steam.mrs,interval=86400,behavior=domain,format=mrs
cn!_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/cn!.mrs,interval=86400,behavior=domain,format=mrs
cn_domain=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/domain/cn.mrs,interval=86400,behavior=domain,format=mrs

google_ip=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/ip/google.mrs,interval=86400,behavior=ipcidr,format=mrs
apple_ip=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/ip/apple.mrs,interval=86400,behavior=ipcidr,format=mrs
telegram_ip=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/ip/telegram.mrs,interval=86400,behavior=ipcidr,format=mrs
netflix_ip=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/ip/netflix.mrs,interval=86400,behavior=ipcidr,format=mrs
cn_ip=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/ip/cn.mrs,interval=86400,behavior=ipcidr,format=mrs
private_ip=type=http,url=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/meta/ip/private.mrs,interval=86400,behavior=ipcidr,format=mrs
